### ISSUE TITLE
Air gaps around snapped window

### ISSUE THREAD

**Issue by antonio1475** [glenviewjeff/HyperWindowSnap#11]
I am getting these empty gaps around the windows snapped with HyperWindowSnap.
Always on the sides, most of the time also the bottom. Top, not always.

I have redownloaded the script just in case.

I have been using it for some time and right now I'm not sure if it just started happening or I had never noticed.
It happens with all apps/windows. Edit: some apps like Telegram & Whatsapp snap fine. Others don't (Windows Explorer, Calculator, Chrome,...).

![HyperWindowSnap](https://user-images.githubusercontent.com/63130724/118786360-072c1e80-b892-11eb-8946-b02e9351d40c.png)

**Comment by glenviewjeff** [comment]
Yes, this is goofy. There must have been a Windows update that makes window dimension inquiries larger than the actual window size. We could kludge this by adding or subtracting pixels from the reported dimensions; I suggested this to another user. 

I wouldn't be surprised if others complain to Microsoft about this apparent defect and it gets fixed in the future, so for the time being I'm not too motivated to work around it myself. My gap seems even bigger than yours; I have a 4k monitor, which if higher resolution than yours would think the gap should be smaller. 

Native Windows gap:

![image](https://user-images.githubusercontent.com/334914/119023869-12ea1480-b968-11eb-8a5b-5a52f234b492.png)

AHK script gap:
![image](https://user-images.githubusercontent.com/334914/119023963-301ee300-b968-11eb-9f82-b378ebc38f64.png)

**Comment by wesuhley** [comment]
I think I was that user Jeff was talking about.
This worked for me (notice the + 7 and - 7, + 15.  7 pixels seems to be the gap most people I've talked to have. But my issue was with ALL windows, not just Google Chrome. So I'm not sure if it will redraw your other windows slightly too large or not. Try it if you want:

SnapActiveWindow(winPlaceVertical, winPlaceHorizontal, winSizeHeight, activeMon) {
    activeWin := WinExist("A")
    activeMon := 0
    WinGet, MinMaxState, MinMax, A.
    If (MinMaxState) {
       WinRestore, A
    }
    
    SysGet, MonitorWorkArea, MonitorWorkArea, %activeMon%

    if (winSizeHeight == "half") {
        height := (MonitorWorkAreaBottom - MonitorWorkAreaTop)/2 + 7
    } else if (winSizeHeight == "full") {
        height := (MonitorWorkAreaBottom - MonitorWorkAreaTop) + 7
	 } else if (winSizeHeight == "third") {
        height := (MonitorWorkAreaBottom - MonitorWorkAreaTop)/3
    }

    if (winPlaceHorizontal == "left") {
        posX  := MonitorWorkAreaLeft - 7
        width := (MonitorWorkAreaRight - MonitorWorkAreaLeft)/2 + 15
    } else if (winPlaceHorizontal == "right") {
        posX  := MonitorWorkAreaLeft + (MonitorWorkAreaRight - MonitorWorkAreaLeft)/2 -7
        width := (MonitorWorkAreaRight - MonitorWorkAreaLeft)/2 + 15
    } else {
        posX  := MonitorWorkAreaLeft
        width := MonitorWorkAreaRight - MonitorWorkAreaLeft
    }

    if (winPlaceVertical == "bottom") {
        posY := MonitorWorkAreaBottom - height + 7
    } else if (winPlaceVertical == "middle") {
        posY := MonitorWorkAreaTop + height
    } else {
        posY := MonitorWorkAreaTop
    }

    WinMove,A,,%posX%,%posY%,%width%,%height%
}

**Comment by wesuhley** [comment]
I'm not sure what's up with the forum insert code feature, but all of that is one copy and paste. It broke it up wierd.

**Comment by antonio1475** [comment]
Wow, thank you both for the great input @glenviewjeff @wesuhley !

@wesuhley your code didn't work directly, so I recreated it manually and found that:

1. Your +-7 & + 15's work great! I have 2 monitors, 1440p & 1080p(portrait), but these adjustments seem to work for both!
2. However, it didn't fix for top & bottom halfs. It seems you didn't add 7 & 15 to:

```
} else {
posX  := MonitorWorkAreaLeft
width := MonitorWorkAreaRight - MonitorWorkAreaLeft
}
```
So I did:
```
} else {
        posX  := MonitorWorkAreaLeft - 7
        width := MonitorWorkAreaRight - MonitorWorkAreaLeft + 15
}
```

Maybe you don't use bottom-top halfs and didn't realize?

3. This part from your code caused errors:

```
, activeMon) {
activeWin := WinExist("A")
activeMon := 0
```

So I didn't change those bits from the original, and it seems to work anyway. So not sure what the impact is?

So in summary, mine sits like:
```
SnapActiveWindow(winPlaceVertical, winPlaceHorizontal, winSizeHeight) {
    activeWin := WinExist("A")
    activeMon := GetMonitorIndexFromWindow(activeWin)
    WinGet, MinMaxState, MinMax, A
    If (MinMaxState) {
       WinRestore, A
    }

SysGet, MonitorWorkArea, MonitorWorkArea, %activeMon%

    if (winSizeHeight == "half") {
        height := (MonitorWorkAreaBottom - MonitorWorkAreaTop)/2 + 7
    } else if (winSizeHeight == "full") {
        height := (MonitorWorkAreaBottom - MonitorWorkAreaTop) + 7
	 } else if (winSizeHeight == "third") {
        height := (MonitorWorkAreaBottom - MonitorWorkAreaTop)/3
    }

    if (winPlaceHorizontal == "left") {
        posX  := MonitorWorkAreaLeft - 7
        width := (MonitorWorkAreaRight - MonitorWorkAreaLeft)/2 + 15
    } else if (winPlaceHorizontal == "right") {
        posX  := MonitorWorkAreaLeft + (MonitorWorkAreaRight - MonitorWorkAreaLeft)/2 -7
        width := (MonitorWorkAreaRight - MonitorWorkAreaLeft)/2 + 15
    } else {
        posX  := MonitorWorkAreaLeft - 7
        width := MonitorWorkAreaRight - MonitorWorkAreaLeft + 15
    }

    if (winPlaceVertical == "bottom") {
        posY := MonitorWorkAreaBottom - height +7
    } else if (winPlaceVertical == "middle") {
        posY := MonitorWorkAreaTop + height
    } else {
        posY := MonitorWorkAreaTop
    }

    WinMove,A,,%posX%,%posY%,%width%,%height%
}
```

Thank you **so** much both again! I won't close it yet in case any additional comments are needed? :)
Edit: wow, script embed really is broken, but it works fine in Preview!

**Comment by glenviewjeff** [comment]
I'll try this out and assuming all is good, I'll update the source; thanks to both of you for contributing!

**Comment by glenviewjeff** [comment]
Also @antonio1475 , the syntax for embedding multiple lines of code on github apparently is to type three single quotes on a line by itself to start, and again to end. See the editing toolbar code button to insert them automatically for you after selecting text. I fixed your note.

**Comment by antonio1475** [comment]
> Also @antonio1475 , the syntax for embedding multiple lines of code on github apparently is to type three single quotes on a line by itself to start, and again to end. See the editing toolbar code button to insert them automatically for you after selecting text. I fixed your note.

Thank you! I did use the toolbar button and it continues to put one quote for me, but lesson learned (not a frequent GitHub user tbh).
I think it was implicit but just in case: HyperWindowSnap is the bomb! I have a Logitech MK850 + M720 mouse with gestures and the works for window management but... yours is better! I use it in combination with MouseGestureL and it's just magic.

**Comment by wesuhley** [comment]
Sorry I've tweaked mine quite a bit, I tried to change it back by memory
and messed it up lol. Welcome!

**Comment by glenviewjeff** [comment]
I agree; I always use a grid of four windows on my big-ass monitor, sometimes making one window take the left and/or right half full height for reading/editing. So I'm constantly using this script. I didn't come up with the concept other than the shrinking and scooting, which I rarely use, primarily because I can't remember the damn keyboard controls. The original author is Andrew Moore.

The shrinking and scooting idea came sort of as a crappy alternative to a great project called ["Code Bubbles"](https://cs.brown.edu/~spr/codebubbles/) which was supposed to be for Eclipse until Microsoft bought it, and then brought it to Visual Studio, and then I believe dissolved the feature. I had been eagerly anticipating it for Eclipse for years, as it seems like a perfect and natural way to edit complex code.

But looking now at the site, it seems the creator turned it into an open source project only a year ago. The Code Bubbles project dates back to 2010. Here's a [video of it in action.](https://www.youtube.com/watch?v=PsPX0nElJ0k&t=14s)

![image](https://user-images.githubusercontent.com/334914/119044223-89464100-b97f-11eb-86ec-04e5741f6472.png)

**Comment by wesuhley** [comment]
Do you guys use the extra wide screen? 4k x 1080? If so I can post my edit
for 4 and 5 columns etc. Also have you guys used Microsoft power toys?

They have a really nice feature called Fancy Zones. It's free and it's
amazing. You can have custom layouts where there's a pre defined area that
you can drag and drop a window. You drag the window title bar like normal
and then hold your right mouse button (or whatever you want to assign it
to) simultaneously. It then pops up a transparent grid of your custom
layout and you just let go of the mouse buttons after you hover over the
box you want it to snap to.

I love it so much

**Comment by glenviewjeff** [comment]
Oh wow, neat, I didn't realize Microsoft updated PowerToys for Windows 10!
They hadn't updated it since ~2009, but had used several of its features
for many years: SyncToy, occasionally their crappy virtual desktops... The
renamer tool looks like it will be easier to use for quick jobs than Bulk
Rename Utility, which is what I usually use.

Fancy zones looks cool, but I'm happy with this tool for what I do.

And wow, Microsoft made a launcher! I finally found my perfect launcher
tool a year or so ago, Keypirinha. Actually, now that I'm looking at this
Microsoft Launcher, it looks like it might be worth a closer look. Looks
like Microsoft forked Wox, which I think I was using prior to Keypirinha.
And check out this piece that's included; the project page
<https://github.com/betsegaw/windowwalker> is hilarious.

**Comment by wesuhley** [comment]
Yep! Exactly. Similar excitement when I found out.

**Comment by glenviewjeff** [comment]
OK I updated the code on the site, thanks for the help and the suggestions, and for making my monitor more presentable without those embarrassing air gaps. Now I can stop using rope caulk to seal them.

**Comment by antonio1475** [comment]
It's funny because when I saw these air gaps I started looking for alternatives (I didn't expect this level of support from you guys!), found PowerToys + FancyZones and even downloaded it.

But because of the size, it felt too much compared to this (since I use AHK for a few other remaps, plus I do office work so I just need to split Gmail, Chat, Meet, Slides... very productive stuff...) so I opened this issue and here we are. I'll take another look when I'm bored anyway.

Thanks again for being so responsive!

**Comment by glenviewjeff** [comment]
Couple of things. I noticed this code change doesn't fix a gap on the left side of my monitor so we need to revise. 

Also, for some reason I had accepted having to scoot new Chrome windows back into place after hitting control-N. I realized this is a Chrome behavior that nobody asked for, so I submitted a request to them to let users turn this "feature" off. 

In the meantime, here's a hotkey script you can use to stop it. It feels kind of out of scope of HyperWindowSnap, but if you guys think it belongs, let me know. Either way, feel free to add it to your personal copies.

```
#IfWinActive ahk_class Chrome_WidgetWin_1
$^n::
h:="ahk_id " WinExist("a")
WinGetPos, X, Y,,,A
Send ^n
WinWaitNotActive, %h%
WinMove, A,, X, Y
Return
#IfWinActive
```

**Comment by antonio1475** [comment]
> Couple of things. I noticed this code change doesn't fix a gap on the left side of my monitor so we need to revise.

Here you go. When I was doing mine, I noticed that too, so I played with X. It was already in the code I posted the other day.
 To be honest the math didn't check out for me but hey, it works...
Basically add -7 to PosX, 3 times
![snap](https://user-images.githubusercontent.com/63130724/119387641-81610680-bcc9-11eb-9e2f-e83c15945605.png)

**Comment by glenviewjeff** [comment]
Thanks @antonio1475! Updated code w/changes. 

Next up, I'm going to try to use unmodified keypad keys to change focus to the corresponding window. Will prevent having to grab the mouse.

**Comment by glenviewjeff** [comment]
If either of you guys are interested, I added window activation (focus) for unmodified keypad keys. I updated it on github but if you want to merge yours manually, here's the code:

```
activateWindow(num) {
	WinGet activeWin, ID, A
	activeMon := GetMonitorIndexFromWindow(activeWin)
	SysGet, MonitorWorkArea, MonitorWorkArea, %activeMon%
	CoordMode, Mouse, Screen
	Switch num {
		Case 7:
			MouseMove MonitorWorkAreaRight / 4, MonitorWorkAreaBottom / 4, 0
		Case 8:
			MouseMove MonitorWorkAreaRight / 2, MonitorWorkAreaBottom / 4, 0
		Case 9:
			MouseMove 3 * MonitorWorkAreaRight / 4, MonitorWorkAreaBottom / 4, 0
		Case 4:
			MouseMove MonitorWorkAreaRight / 4, MonitorWorkAreaBottom / 2, 0
		Case 6:
			MouseMove 3 * MonitorWorkAreaRight / 4, MonitorWorkAreaBottom / 2, 0
		Case 1:
			MouseMove MonitorWorkAreaRight / 4, 3 * MonitorWorkAreaBottom / 4, 0
		Case 2:
			MouseMove MonitorWorkAreaRight / 2, 3 * MonitorWorkAreaBottom / 4, 0
		Case 3:
			MouseMove 3 * MonitorWorkAreaRight / 4, 3 * MonitorWorkAreaBottom / 4, 0
	}
	Sleep, 100
	MouseGetPos,,, hwnd 
	WinActivate, ahk_id %hwnd%
}

; Numpad unmodified, activate corresponding window
Numpad1::activateWindow(1)
Numpad2::activateWindow(2)
Numpad3::activateWindow(3)
Numpad4::activateWindow(4)
Numpad6::activateWindow(6)
Numpad7::activateWindow(7)
Numpad8::activateWindow(8)
Numpad9::activateWindow(9)

```

**Comment by wesuhley** [comment]
Nice, thank you. I actually had been doing something similar with mine.
Made a couple hotkeys that open multiple programs and apps and snaps them
to the spots I want using the snapactivewindow method. Finding the path to
an app (not a program exe file) was super annoying though lol. Finally
dragged them into notepad to see the full path. End result is one button
that opens and places windows where I like them. I know there are paid
software that does this, but it was fun to do it in autohotkey

**Comment by glenviewjeff** [comment]
Very nice. To be clear, the number keys now just change the focus whatever
window is at the position you select. So for instance, if you hit numeric
keypad 9, the window at the top right will become active, and then you can
either type or scroll or whatever you want.

**Comment by wesuhley** [comment]
Ahh I see.
